package project.euler;
import java.util.ArrayList;
import java.util.Iterator;

/* Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 */

public class Euler2_1 {
	public static void main(String aregs[]){
		// find the fibonacci number first . . 
		// put them in an array ??
		// put them in an array list ??
		
		int sumOfEvenNumbers = 0;
		ArrayList<Integer> myList = new ArrayList();
		myList.add(1);
		myList.add(2);
		
		
		while (Integer.parseInt((myList.get(myList.size()-1)).toString()) < 4_000_000) {
			int listSize = myList.size();
			int lastIndex = listSize - 1;
			int x1 = myList.get(lastIndex);
			int x2 = myList.get(lastIndex-1);
			int sum = x1 + x2;
			if (sum > 4_000_000)
				break;
			System.out.println(sum);
			myList.add(sum);
		}
			
		// Now sum the even number in the list . . . 
		Iterator<Integer> myListIterator = myList.iterator();
		while (myListIterator.hasNext()) {
			int x = myListIterator.next();
			if (x % 2 == 0)
				sumOfEvenNumbers += x;
			
		}
		
		System.out.println("Sum of even numbers = " + sumOfEvenNumbers);
		
	}
	
}
